version: '3.8'

services:
  # 应用服务
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - GIN_MODE=release
    volumes:
      - ./logs:/root/logs
    networks:
      - bossfi-network
    restart: unless-stopped

  # PostgreSQL数据库
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bossfi
      POSTGRES_USER: bossfier
      POSTGRES_PASSWORD: bossfier
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - bossfi-network
    restart: unless-stopped
    command: postgres -c log_statement=all -c log_destination=stderr

  # Redis缓存
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bossfi-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Nginx反向代理（生产环境）
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - bossfi-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  bossfi-network:
    driver: bridge 