# 服务器配置
[server]
port = 8080
mode = "debug"  # debug, release, test
read_timeout = "60s"
write_timeout = "60s"

# 数据库配置
[database]
driver = "mysql"
host = "localhost"
port = 3306
database = "bossfi"
username = "bossfier"
password = "bossfier"
charset = "utf8mb4"
parse_time = true
loc = "Local"
max_idle_conns = 10
max_open_conns = 100
conn_max_lifetime = "3600s"

# Redis配置
[redis]
host = "localhost"
port = 6379
password = ""
db = 0
pool_size = 10
min_idle_conns = 2

# JWT配置
[jwt]
secret = "3lmeQCb168BeB/ESaO2XnP8/r/oxSoo9GogOjO9TCKNw2rlLZBYKVEj0HQBINVJJXv6JkJ51sfspArgcWuSVAA=="
expire_time = "24h"

# 日志配置
[logger]
level = "debug"
filename = "./logs/app.log"
max_size = 100
max_age = 30
max_backups = 5
compress = true

# 区块链配置
[blockchain]
network = "testnet"  # mainnet, testnet
confirmation_blocks = 6
gas_price = 20000000000  # 20 gwei
gas_limit = 21000

# 安全配置
[security]
rate_limit = 100  # requests per minute
cors_origins = ["*"]
trusted_proxies = ["127.0.0.1"] 