basePath: /api/v1
definitions:
  controllers.GetNonceRequest:
    properties:
      wallet_address:
        example: 0x1234567890123456789012345678901234567890
        type: string
    required:
    - wallet_address
    type: object
  controllers.GetNonceResponse:
    properties:
      message:
        example: Welcome to BossFi!...
        type: string
      nonce:
        example: abc123def456
        type: string
    type: object
  controllers.LoginRequest:
    properties:
      message:
        example: Welcome to BossFi!...
        type: string
      signature:
        example: 0x1234567890abcdef...
        type: string
      wallet_address:
        example: 0x1234567890123456789012345678901234567890
        type: string
    required:
    - message
    - signature
    - wallet_address
    type: object
  controllers.LoginResponse:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
      user: {}
    type: object
  routes.HealthResponse:
    properties:
      message:
        example: BossFi Backend is running
        type: string
      status:
        example: ok
        type: string
      system:
        additionalProperties:
          type: string
        type: object
      timestamp:
        example: "2025-06-26T15:50:00Z"
        type: string
      trace_id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      uptime:
        example: 2h30m45s
        type: string
      version:
        example: 1.0.0
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@bossfi.com
    name: BossFi Team
    url: https://www.bossfi.com
  description: BossFi区块链后端API服务，支持钱包登录、用户管理、区块链数据同步等功能
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://www.bossfi.com/terms
  title: BossFi Backend API
  version: 1.0.0
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: 使用钱包签名进行登录验证，验证成功后返回JWT令牌
      parameters:
      - description: 登录信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/controllers.LoginResponse'
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 认证失败
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 钱包签名登录
      tags:
      - 认证
  /auth/logout:
    post:
      consumes:
      - application/json
      description: 用户登出，清除服务器端会话信息
      produces:
      - application/json
      responses:
        "200":
          description: 登出成功
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未认证
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: 用户登出
      tags:
      - 认证
  /auth/nonce:
    post:
      consumes:
      - application/json
      description: 前端调用此接口获取需要签名的消息和 nonce，用于钱包登录
      parameters:
      - description: 钱包地址信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.GetNonceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功返回签名消息和nonce
          schema:
            $ref: '#/definitions/controllers.GetNonceResponse'
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 获取用于钱包签名的消息和 nonce
      tags:
      - 认证
  /auth/profile:
    get:
      consumes:
      - application/json
      description: 获取当前登录用户的详细个人信息
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未认证
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 用户不存在
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: 获取用户个人信息
      tags:
      - 认证
  /health:
    get:
      consumes:
      - application/json
      description: 检查服务器是否正常运行，返回系统状态信息和TraceID
      produces:
      - application/json
      responses:
        "200":
          description: 服务正常
          schema:
            $ref: '#/definitions/routes.HealthResponse'
      summary: 健康检查
      tags:
      - 系统
schemes:
- http
- https
securityDefinitions:
  Bearer:
    description: 输入Bearer {token}
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
